
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: muse
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: app-template-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/museofficial/muse
              tag: pr-1256
            env:
              DISCORD_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: muse-secret
                    key: DISCORD_TOKEN
              YOUTUBE_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: muse-secret
                    key: YOUTUBE_API_KEY
              SPOTIFY_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: muse-secret
                    key: SPOTIFY_CLIENT_ID
              SPOTIFY_CLIENT_SECRET: 
                valueFrom:
                  secretKeyRef:
                    name: muse-secret
                    key: SPOTIFY_CLIENT_SECRET
              BOT_ACTIVITY_TYPE: LISTENING
              BOT_ACTIVITY: to Outplays
    persistence:
      data:
        enabled: true
        type: emptyDir


    service:
      main:
        controller: main
        enabled: false
        ports:
          http:
            enabled: false
            port: 80