apiVersion: v1
kind: Secret
metadata:
    name: muse-secret
    namespace: default
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:JD8ckg/JHkgP+BQmD7FnMR8jhd9K3cO2Ys5pwtGtdnXCtYuPuLNRgO/k9Pq/o05Zr/mg9MbHaysaDFKpPyWDDkim3eGArjhq,iv:/sf07ZelQDtMw7EkBRlMigbdBSGLYV+qZJxGG+xSL/Q=,tag:vnHn5Zin9yLAq02ZeyUHkA==,type:str]
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:moYBhuQocntbybMNJ2FtZwS9ZYKbenQ//g0WkSuOXC2Kxnl8J9od,iv:/NmS2Rlmvkv1fOE8+Lalv/6CiVHKYsa5Pf82Ng0HtDY=,tag:MAcRxFatAdugEVXNn6eUNA==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:pfMBKuZHtRz+ORBbhglTVtUNlOxj11uBZ8RCcErGZO4=,iv:nJi1ItO4npz3YrIvECqQCO4mNmU3bO+g7+3tdXqdbPE=,tag:nBiP5TYgg/bYgo2xyXdb3Q==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:JvCr02yIXFt4uCuizO0X/fWwUtP5I4JoJorFSnrocoY=,iv:3YJZYzc6/wf8zkPDCmpALKxWtUKgbWAq7WUPIbKs8LQ=,tag:Ldi2RyhnTId3gh7iNV1JLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY2U4K1VkRUxHa29RVERW
            TEVVNG5SKy9HTnVXWWJLb1NwTEFGbUZBUkVJCjhFamMvd05IS0Q3cW05YXIwN1Bp
            Ty9SUTFBQkc3NFhZMVFxci9XeVgyM1kKLS0tIHZCOU1oWGJocm9QZU5pTldIQ0oy
            S1NieGw1WnEwT1Qwd1ZzWVJHQVluNncKa/R6F4Ve1Qra6eTyveDp/QzvPf+8b3Zr
            ROG3fFMJ2B0aNt/akbAPwclRBqFC0PyJxpO4Ys5QzP8PYmA6TfnzUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T13:38:39Z"
    mac: ENC[AES256_GCM,data:sE85NHZPEuwnStwELVtLGsXlRl7c9ACGLpPIjW7egRtUdQEELg8Sr66H5NKmwrpZxmFJCFUlPO66DMRWnHIdOIXrbbdrzfx7TgvYHp/CiuOWYzKmZWKE1JFlVD5lfoK2oYx5LKAYurAUyS57SuH5FRXFmuGFFLAkQAfmgJYPZGc=,iv:AfHq85UyB6YRyfC7ur5gAiHKnmW29rc7CoZQ6LSJcec=,tag:2blqfjJ6qiaM8rC9jy37Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
