---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: prometheus-pv
  storageClassName: csi-cephfs-sc