apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ipam-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.stacktonic.au/stackhelm/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  type: "oci"
  interval: 1h
  timeout: 3m
  url: oci://registry-1.docker.io/bitnamicharts/mysql