apiVersion: v1
type: Opaque
kind: Secret
metadata:
    name: docker-config
    namespace: default
data:
    config.json: ENC[AES256_GCM,data:YqPKzHNHk0TGXJeU0vKE2JNEuTWgj+WfrQjEXXBDtimwL7q+RGAqoq9dczEDU7TfwsunAWu0esoexu1/bKEzTbXy0eQ7rVQZRX1hcGCQ6rC1mPRSvW2nuax4f9kfd61skVvxQ46h7XTUE8JmcITrUZrY8DFVRtdxWQY1UA23c9oHznY4,iv:DkDDvPmLTaxprN6CylJa00hFAFC9ZTLpq1TKMJmWy8s=,tag:gd4DNhV+rQ/LM7k/7q75Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdEdCUktTMEcreUZVRXhp
            ZEJ0SzYxOTh4WTVEWU5MT2hyd3EzajZRVVhrClpiemd4R1lpajdDN1pWS2dsSllj
            eU9LRTR6QUdqbW1zcWs2b0xtaTAzV00KLS0tIG5CZ2IrMk03TWE1YkpvcncvWlUy
            VzllT2ptcnNaaVZnakVTOVpDaEFaekkKbJ1RxTzzJigNicVEA5hgCLblgE7/0gWR
            9hqI40YZlUCRjpXfJxm0ooztd6ib3NLfFi71LXA/lVQ/6LvbbiNJ1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T10:01:47Z"
    mac: ENC[AES256_GCM,data:td9rgCbg3NtQZb4Q0tC+4O/nSM7eNnTXUXRa+nxC6nTmy5E/IfQ2Ib0pS2+refb1kx5MDLcYky96T07hv4JsD+XCjZujMg897w+FwiyeFVRGpXXDDyCHsXpblzJuVbYfpt3fteBDQ99rXZPfgfcPt5F2zZ5eVF2iuJ0559B9JUw=,iv:xaqSmZmlhGvtTnV3Q90a112ttzfSXVWntCLpW7wXz7w=,tag:xfCy0V8S5IGhUBIPlHVQAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
