apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: csi-cephfs-sc
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi-cephfs
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "2e4a3e28-4d59-45d4-8705-4b322a4b953c"
      "fsName": "cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/kubernetes/jenkins
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: jenkins-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem