apiVersion: v1
kind: Secret
metadata:
    name: jenkins-admin-secret
    labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/component: controller
type: Opaque
stringData:
    jenkins-admin-user: ENC[AES256_GCM,data:0aoI5Aze,iv:ATr4n5VSvld+bdGMmB0CS7gsDNknJyB1SUzgFFRPpFE=,tag:5QW9XHJm736m8FnG/AnU/w==,type:str]
    jenkins-admin-password: ENC[AES256_GCM,data:AA0DJ+T6F+Vsh+jXjQ==,iv:tUXxtMwVgTkx2aJBeBBSnLn8yYb3ksYKv6csfIKpK3w=,tag:2K1xXyhH3Sqwo8NauqaatQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWFdHZ2RkR3dJOUtoa3lC
            ZGVYVm41WmtDUVJLSXpTVEdFeVNHN2ZwOHhvCjV1RFNTZVZ0OTB2SUdwd0k1NWRs
            VzZUclVjc3kxWWdhRjlKQ2NmTDJFUU0KLS0tIG56YmRQa2kvaWQ0VGFSbXZxZmFt
            STExSXZ3TWhCMmhkR1ZnSmJtRFpNZmMKCjUgupnpS+wDEg/3r46qauE+RT/SzOf9
            l4toE+D4uG6+FixDmXx54mRFE+xcrx+nSnPfmoEuidjV8WYqLtijqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T02:05:33Z"
    mac: ENC[AES256_GCM,data:lULKTWaSQMIMMV7Eea3xTFj0Fq2Diw+cdURHqXrUO+ANWR+EJIapxjc+KULTy4Xf/9GDeDQZDTN4aa8DMgo1frnxvUtSq/OTfrvx8IcNoW2QJCQ199H/EUQh2Ad+kvBIDat9b7swuwI2WW5E0tthXsS4zgw863VZA/ImMghoZGQ=,iv:k8gD8MvU2zQLv/0sa3pCVpvITOE1wJn2VN9VJsV+BbY=,tag:9p9Uy0CDst5nfJz5Os+64Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
