apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system  # References the same repo
  path: ./secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age