
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pdm
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: app-template-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/aksine/proxmox-datacenter-manager-docker/pdm
              tag: b7792c
                # -- environment variables.

    service:
      main:
        controller: main
        ports:
          https:
            port: 8443
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: true
        hosts:
          - host: pdm.aksine.lcl
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: https


    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      data:
        enabled: true
        existingClaim: pdm-pvc
        globalMounts:
              - path: /var/lib/pdm


