---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aksign.am@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: aksign.am@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-secret
              key: cloudflare-api
        selector:
          dnsZones:
            - "aksine-am.com"