apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - mail-config-pv.yaml
  - mail-config-pvc.yaml
  - mail-data-pv.yaml
  - mail-data-pvc.yaml
  - mail-logs-pv.yaml
  - mail-logs-pvc.yaml
  - mail-state-pv.yaml
  - mail-state-pvc.yaml
