---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-data-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: mail-data-pv
  storageClassName: csi-cephfs-sc