apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:8Mypn4yhiXWcZfLDdN1VUca/PwF8UYqWa8u7XaTgSydN1IxTwlY9/g==,iv:EDWwKsPVbIbpB+k+QXEdAPcujATgNv3UUF9G7UnY2mI=,tag:ci6KlcV5aCMRDe5+22TgoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cjJDemRxeEpwYzJ4T0Jp
            WldDRnhVWnQrNDk5ckN1Y3g4YTUwMzIyWWpRCmprc0lNUXJDOUh6NllDSGgvSWl0
            T1dTbTFGZk9lcWZ3bHJSQjZsbjdOOG8KLS0tIHE1b3I5S3ZJMzVWK2hYVlhIM3p3
            a0lUa1RqNzNrWjR4QWMyUnY5RlpQbFkKQuRYzTQyXw93/BhWk1p68HtlnhF5q5Nq
            HSemhu20Ry9fD/AbILMxzIHe6TS+xrrzTrzlPiVmtjJIPZti5pcTdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T04:22:07Z"
    mac: ENC[AES256_GCM,data:gpgtMtF8vI98xv3tXkERRnHoJbTbbbD/fLivDiR4N/FmGa6wsOMS4eZ+nZK8thTHk/KAFs84tJ+hV0y54Chy4uGM4ej7D2e5jR/dDfvsTODhmSWlZUY7q5tWY0J1xNfoi0e/jMysxkWMYIlVoNAKja1PEcnDXapC60sRLYVe6bM=,iv:DN5LV4tJnFM6tlAzLUkf9F44EIqgBqqhHApZrBZazU0=,tag:kbdtU0fmysSr47t+63yWbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
