apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-api: ENC[AES256_GCM,data:ID8JRkFkyKp7yiYMbaPSIa/O6MeDwSY19BoVs6vuVoxYj82I/Q==,iv:/HnWPXzBNweDMI+G30VdbI0CMes+EaAtNCNhKRMGI6g=,tag:mjhPBiAC/M4BNf7De7nspA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cjJDemRxeEpwYzJ4T0Jp
            WldDRnhVWnQrNDk5ckN1Y3g4YTUwMzIyWWpRCmprc0lNUXJDOUh6NllDSGgvSWl0
            T1dTbTFGZk9lcWZ3bHJSQjZsbjdOOG8KLS0tIHE1b3I5S3ZJMzVWK2hYVlhIM3p3
            a0lUa1RqNzNrWjR4QWMyUnY5RlpQbFkKQuRYzTQyXw93/BhWk1p68HtlnhF5q5Nq
            HSemhu20Ry9fD/AbILMxzIHe6TS+xrrzTrzlPiVmtjJIPZti5pcTdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T02:38:56Z"
    mac: ENC[AES256_GCM,data:VsUkCz2JkIZhKjiatYdZ1k9aFnNjwkQaVXOVmrgCIewT1V1Y83iOI5k8cHuYj5s4ieFs8bFGpthuAn0DWjAHqeF/82UXfjiDTUdKNv37a3inVkfxIrzLZKQitmy6erpfo3vx10ztpx+/Aj5qsnr6z5VIklr7WDa/zARQ2MfsuqU=,iv:RkKoevgO5OfZnN9TSN0LObu+jlFRevrn4ddDGox+XDc=,tag:wSI/mJNpgtwK3grkqN8pPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
