
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meshcentral
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: app-template-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: typhonragewind/meshcentral
              tag: 1.1.48
                # -- environment variables.
                # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            env:
              # -- Set the container timezone
              TZ: Australia/Melbourne
              NODE_ENV: production
              HOSTNAME: meshcentral.aksine.lcl
              ALLOW_NEW_ACCOUNTS: "false"

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: true
        hosts:
          - host: meshcentral.aksine.lcl
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http


    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        type: configMap
        name: meshcentral-config
        advancedMounts:
          main :
            main :
              - path: /opt/meshcentral/meshcentral-data/config.json
                subPath: config.json
      data:
        existingClaim: meshcentral-pvc
        globalMounts:
          - path: /root
            subPath: rootdir
          - path: /opt/meshcentral/meshcentral-data
            subPath: data
          - path: /opt/meshcentral/meshcentral-files
            subPath: userfiles
          - path: /opt/meshcentral/meshcentral-backups
            subPath: backups