---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-config
  namespace: default
data:
  config.json: |
    {
      "settings": {
        "port": 8080,
        "redirPort": 0,
        "TlsOffload": true
      },
      "domains": {
        "": {
          "userQuota": 1048576,
          "meshQuota": 248576,
          "newAccounts": 0
          "allowedOrigin": "meshcentral.aksine.lcl"
        }
      }
    }