apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/aus/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
