apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
  namespace: ceph-csi-cephfs
spec:
  interval: 5m
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3