---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: obs-pv
  storageClassName: csi-cephfs-sc