apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    credentials.json: ENC[AES256_GCM,data:EP8jCNf9HYTeTeLQ1wHF0pcB66c++slZwo2maCZP6DYPjGoiDe4FF1s59NN8Gu6QFXlU0iaI2Lup3l5R4yvJC+85ffRlcRFozUmygpxtABhZoGuGj4SVAwFmeyaIJFU1TwqPx7k5dHuJw5OStU4/U8cJIV1Lh2xCE5ViksHybLPcynvD9GRcSkmM6jU70hT2n9r4wmYo1b1OYIiRKld0S/7yFCdjxUxuUqswDsw=,iv:F1SCXNPF3ktHgrGYcT3W19ysw8Er4VUsYxBlse0QNw8=,tag:+OZo+ZDS4zmYm1i6qTxK9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOHVIbW5CVW5VaDZON2Vs
            YmZFQ3Y0ZS9wTEZEZ0dseFh0YVg2Q0RMR2xnClZjck5yWlIrWC9JMGdzcEgwQnQv
            T2UyMll2NGZ0RVJxbUxvblNqRFlkTWMKLS0tIGZlSXNUUWFnam4wNlhjM3NHUDJ5
            TmxKNy9DN1BWUW9iTFRZQVp2RjhhaWcKEXNpsq4DMkPCGREzCHdM08HplmBUbUPl
            EpS6th5QK68YTJi5dniDTnl2HSgepVNlwiM3cowORkoCcnFiDciyiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T11:11:43Z"
    mac: ENC[AES256_GCM,data:yk33r01s7LIRdgQ6ws8UsVcrld2h9v8lBoXXgmCghgpyRvZYdweylGPUeseJOSKJ4FnrqtskKddJ5IU7ygcGQqd0Alyhx+HRBef9mj+aerrrRqmWVFfrYeKXuJHZHCtVYWtrqcwiiQzeVTwwGxoPyvP/A3Sq9+J/jGmprIY+F8c=,iv:/myZ8Vj+O+yIXmOqQOK/WjFQOe38Q87LCFYtAGdKrcw=,tag:EoGlQxh5tvW/pude0pLYZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
